---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-card-template" (include "app.name" .) }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
binaryData:
  card.tmpl: |-
  {{- include "app.cardTemplate" . | b64enc | nindent 4 }}
{{- with .Values.connectorsWithCustomTemplates }}
  {{- include "app.customTemplates.tmpl" . | nindent 2 }}
{{- end }}
