name: Pull request for documentation changes

on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'README.md'
      - '.markdownlint.yaml'
      - '.vale.ini'
      - '**/*.md'
  workflow_dispatch: {}

jobs:
  doc_qa:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    uses: stakater/.github/.github/workflows/pull_request_doc_qa.yaml@v0.0.181
    with:
      MD_CONFIG: .github/md_config.json
      DOC_SRC: README.md
      MD_LINT_CONFIG: .markdownlint.yaml
