name: Pull Request - Code Coverage
on:
  pull_request:
    branches: 
      - "main"

jobs:
  code_coverage:
    name: Check Code Coverage
    uses: ./.github/workflows/_test.yaml
    with:
      TEST_COVERAGE_FILE: cover.out
